### ISSUE TITLE
Netflix picture in picture no longer working

### ISSUE THREAD

**Issue by ximi** [amarcu5/PiPer#38]
In the past few days picture in picture mode no longer seems to work. The button shows up, but clicking on it has no effect.

Youtube and other sites work just fine.

There are no errors in the javascript console.

**Comment by amarcu5** [comment]
Thanks for the bug report, this is fixed in the latest version.

Safari Extension Gallery is a version behind at the time of writing (expecting approval shortly). If you’re willing to sacrifice auto updating you can get the latest stable version [here](https://raw.githubusercontent.com/amarcu5/PiPer/master/out/PiPer.safariextz).
